### ISSUE TITLE
question: generate a config from an example file

### ISSUE THREAD

**Issue by justin2004** [ShadowTraffic/shadowtraffic-examples#5]
is there a process that can generate a config file from some example data?

**Comment by MichaelDrogalis** [comment]
Hey @justin2004. AI to the rescue! 🚀

I trained [a custom GPT](https://chatgpt.com/g/g-Am8LNJj8M-shadowtraffic-helper) on ShadowTraffic so you can ask it to write configs for you based on example data or random ideas.

Like any other LLM, it's not perfect and hallucinates sometimes, but it's pretty good.

**Comment by justin2004** [comment]
@MichaelDrogalis , my man! thanks. i'll try it!

**Comment by justin2004** [comment]
@MichaelDrogalis , i gave it a try but the config files it produced had errors -- even after many follow on prompts. 

i think that shadow traffic is missing a `bootstrap` command that can produce a naive shadow traffic config file from json schema. it is easy to derive a json schema file from an example json file.

without such a `bootstrap` command i think potential users (including me) are going to try this tool but bounce off of it because learning to make a simple config file (that produces data that conforms to some known schema) seems like more of an effort than they are willing to put in.

**Comment by MichaelDrogalis** [comment]
Sorry to hear that! I think that'd be a good product addition.

Drop me a quick email at `michael@shadowtraffic.io` and I'll bounce some ideas off you as I get into it.

**Comment by MichaelDrogalis** [comment]
Added in [0.12.6](https://docs.shadowtraffic.io/changelog/#0126).
